language: cpp
compiler: gcc
script:
  - cmake
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all

addons:
  apt:
    packages:
    - libvlc-dev 
    - libopencv-dev 
    - libqt4-private-dev
    - ninja-build
  sonarcloud:
    organization: "bshm-github"
