language: cpp
compiler: gcc
script:
  - cmake .
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - sonar-scanner -Dsonar.projectKey=bshm_halloweeneyes -Dsonar.organization=bshm-github -Dsonar.sources=. -Dsonar.cfamily.build-wrapper-output=bw-output -Dsonar.host.url=https://sonarcloud.io

addons:
  apt:
    packages:
    - libvlc-dev 
    - libopencv-dev 
    - libqt4-private-dev
    - ninja-build
  sonarcloud:
    organization: "bshm-github"
